---
# tasks file for monitoring_agent
- name: create node_exporter user 
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /sbin/nologin
    system: yes
    create_home: no 

- name: Download Node Exporter archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/opt/node_exporter/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: '0644'

- name: Extract Node Exporter archive
  ansible.builtin.unarchive:
    src: "/opt/node_exporter/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: /opt/node_exporter
    remote_src: yes

- name: Install Node Exporter binary
  ansible.builtin.copy:
    src: "/opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_install_dir }}/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: '0755'
    remote_src: yes

- name: Install Node Exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: start the service and enable it at boot
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
